hakam_multi_tenancy:
  tenant_database_className:  App\Entity\Main\CustomerDbConfig     # tenant dbs configuration Class Name
  tenant_database_identifier: id                                 # tenant db column name to get db configuration
  tenant_connection:                                             # tenant entity manager connection configuration
    host:     127.0.0.1
    driver:   pdo_mysql
    charset:  utf8
    dbname:   customer                                           # default tenant database to init the tenant connection
    user:     root                                              # default tenant database username
    password: null                                              # default tenant database password
    server_version: 8.0.29                                         # mysql server version

  tenant_migration:                                             # tenant db migration configurations, Its recommended to have a different migration for tenants dbs than you main migration config
    tenant_migration_namespace: DoctrineMigrations\Customer
    tenant_migration_path: migrations/Customer
  tenant_entity_manager:                                        # tenant entity manger configuration , which is used to manage tenant entities
    mapping:
      type:   annotation                                        # mapping type default annotation
      dir:   '%kernel.project_dir%/src/Entity/Customer'           # directory of tenant entities, it could be different from main directory
      prefix: App\Entity\Customer                                # tenant entities prefix  ex "App\Entity\Tenant"
      alias:   Customer                                           # tenant entities alias  ex "Tenant"